name = "doughatcher-link-preview"
workers_dev = true
main = "src/index.js"
compatibility_date = "2025-09-01"

routes = [
  { pattern = "preview.doughatcher.com/*", zone_name = "doughatcher.com" }
]

[[kv_namespaces]]
binding = "PREVIEW_CACHE"
id = "f48049994ef74c418fe7b8f491f6e905"

[observability]
enabled = true
